### ISSUE TITLE
will you support null-safety?

### ISSUE THREAD

**Issue by tagby-haedongJeon** [emanuel-braz/keyboard_overlay#2]

**Comment by emanuel-braz** [comment]
@tagby-haedongJeon yes!

**Comment by emanuel-braz** [comment]
@tagby-haedongJeon probably I'll gonna migrate to that new package as dependency
[pls take a look at this issue (keyboard_visibility)](https://github.com/adee42/flutter_keyboard_visibility/issues/71#issuecomment-844370892)

![Screen Shot 2022-03-15 at 22 21 52](https://user-images.githubusercontent.com/3827308/158498064-591fd1ee-9bd5-4e2a-839f-ae3af63b9447.png)
